zuul:
  prefix: /api
  routes:
    chat:
      path: /chat/**
      serviceId: chat
      customSensitiveHeaders: true
  ws:
    brokerages:
      chat:
        end-points: /ws
        brokers: /topic
        destination-prefixes: /app